{% set name = "pyobjc-framework-FSEvents" %}
{% set version = "10.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f5dee8cfbd878006814db264c5f70aeb1a43c06620e98f628ca6c0008beb1b1d

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [not osx or (arm64 and py < 39)]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - pip
    - python
    - setuptools
  run:
    - python
    - pyobjc-core {{ version }}
    - pyobjc-framework-cocoa {{ version }}

test:
  imports:
    - FSEvents

about:
  home: https://bitbucket.org/ronaldoussoren/pyobjc
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Wrappers for the framework FSEvents on macOS

extra:
  recipe-maintainers:
    - larsoner
    - hoechenberger
    - xhochy
