{% set name = "pyobjc-framework-FSEvents" %}
{% set version = "11.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pyobjc_framework_fsevents-{{ version }}.tar.gz
  sha256: d29157d04124503c4dfa9dcbbdc8c34d3bab134d3db3a48d96d93f26bd94c14d

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [not osx or (arm64 and py < 39)]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - pip
    - python
    - setuptools
  run:
    - python
    - pyobjc-core {{ version }}
    - pyobjc-framework-cocoa {{ version }}

test:
  imports:
    - FSEvents

about:
  home: https://github.com/ronaldoussoren/pyobjc
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Wrappers for the framework FSEvents on macOS

extra:
  recipe-maintainers:
    - larsoner
    - hoechenberger
    - xhochy
